# Stimulus parameters for detecting noise level with theta vs theta+1.5*JND_theta
c: 0.145
sscale: 2.6
noise_condition: H-H
sigma: 2
stimulus_0:
  label: hue_8p
  standard: 337.5
  test: 343.5
  ref: 347.5
  stairType: quest
  startVal: 5.0
  min_val: 1.0
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63