c: 0.145
sscale: 2.6
dlum: 0
noise_condition: H-H
stimulus_1:
  label: x_2p
  standard: 292.5
  test: 297.5
  ref: 302.5
  stairType: quest
  startVal: 5.0
  min_val: 1.0
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_2:
  label: y_2p
  standard: 202.5
  test: 207.5
  ref: 212.5
  stairType: quest
  startVal: 5.0
  min_val: 1.0
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_3:
  label: y_1p
  standard: 22.5
  test: 27.5
  ref: 32.5
  stairType: quest
  startVal: 5.0
  min_val: 1.0
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_4:
  label: x_1p
  standard: 112.5
  test: 117.5
  ref: 122.5
  stairType: quest
  startVal: 5.0
  min_val: 1.0
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63