monitor:
  name: VIEWPixx_2000A
  size:
  - 1920
  - 1200
  width: 48.4
  distance: 57
depthBits: 10
patch_nmb: 16
patch_size: 0.75
ref_size: 0.8
field_size:
- 4
- 4
ref.pos:
- 0
- 2.5
standard.xlim:
- -5
- -2
standard.ylim:
- -4
- -1
test.xlim:
- 2
- 5
test.ylim:
- -4
- -1
trial_nmb: 20
trial_dur: 1
