stimulus_0:
  label: hue_2p
  standard: 67.5
  ref: 77.5
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  std: 0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_1:
  label: hue_2m
  standard: 67.5
  ref: 57.5
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  std: 0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63