c: 0.145
sscale: 2.6
noise_condition: L-L
sigma: 2
stimulus_0:
  label: hue_3m
  standard: 112.5
  leftRef: 122.5
  rightRef: 102.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_1:
  label: hue_7p
  standard: 292.5
  leftRef: 302.5
  rightRef: 282.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_2:
  label: hue_4m
  standard: 157.5
  leftRef: 167.5
  rightRef: 147.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_3:
  label: hue_7m
  standard: 292.5
  leftRef: 302.5
  rightRef: 282.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_4:
  label: hue_2m
  standard: 67.5
  leftRef: 77.5
  rightRef: 57.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_5:
  label: hue_6m
  standard: 247.5
  leftRef: 257.5
  rightRef: 237.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_6:
  label: hue_3p
  standard: 112.5
  leftRef: 122.5
  rightRef: 102.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_7:
  label: hue_5p
  standard: 202.5
  leftRef: 212.5
  rightRef: 192.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_8:
  label: hue_1m
  standard: 22.5
  leftRef: 32.5
  rightRef: 12.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_9:
  label: hue_5m
  standard: 202.5
  leftRef: 212.5
  rightRef: 192.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_10:
  label: hue_6p
  standard: 247.5
  leftRef: 257.5
  rightRef: 237.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_11:
  label: hue_8m
  standard: 337.5
  leftRef: 347.5
  rightRef: 327.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_12:
  label: hue_2p
  standard: 67.5
  leftRef: 77.5
  rightRef: 57.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_13:
  label: hue_1p
  standard: 22.5
  leftRef: 32.5
  rightRef: 12.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_14:
  label: hue_4p
  standard: 157.5
  leftRef: 167.5
  rightRef: 147.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_15:
  label: hue_8p
  standard: 337.5
  leftRef: 347.5
  rightRef: 327.5
  std: 0.0
  stairType: quest
  startVal: 5.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
