c: 0.12
sscale: 2.6
dlum: 0
noise_condition: L-L
sigma: 2
stimulus_0:
  label: hue_2m
  standard: 45.0
  leftRef: 55.0
  rightRef: 35.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_1:
  label: hue_2p
  standard: 45.0
  leftRef: 55.0
  rightRef: 35.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_2:
  label: hue_5m
  standard: 180.0
  leftRef: 190.0
  rightRef: 170.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_3:
  label: hue_5p
  standard: 180.0
  leftRef: 190.0
  rightRef: 170.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_4:
  label: hue_1m
  standard: 0.0
  leftRef: 10.0
  rightRef: -10.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63
stimulus_5:
  label: hue_1p
  standard: 0.0
  leftRef: 10.0
  rightRef: -10.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 10
  pThreshold: 0.63