c: 0.12
sscale: 2.6
dlum: 0
noise_condition: L-L
sigma: 2
stimulus_0:
  label: hue_8p
  standard: 315.0
  leftRef: 325.0
  rightRef: 305.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_1:
  label: hue_8m
  standard: 315.0
  leftRef: 325.0
  rightRef: 305.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_2:
  label: hue_7m
  standard: 270.0
  leftRef: 280.0
  rightRef: 260.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_3:
  label: hue_5p
  standard: 180.0
  leftRef: 190.0
  rightRef: 170.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_4:
  label: hue_7p
  standard: 270.0
  leftRef: 280.0
  rightRef: 260.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_5:
  label: hue_6p
  standard: 225.0
  leftRef: 235.0
  rightRef: 215.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_6:
  label: hue_3p
  standard: 90.0
  leftRef: 100.0
  rightRef: 80.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_7:
  label: hue_4m
  standard: 135.0
  leftRef: 145.0
  rightRef: 125.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_8:
  label: hue_1p
  standard: 0.0
  leftRef: 10.0
  rightRef: -10.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_9:
  label: hue_3m
  standard: 90.0
  leftRef: 100.0
  rightRef: 80.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_10:
  label: hue_4p
  standard: 135.0
  leftRef: 145.0
  rightRef: 125.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_11:
  label: hue_5m
  standard: 180.0
  leftRef: 190.0
  rightRef: 170.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_12:
  label: hue_2m
  standard: 45.0
  leftRef: 55.0
  rightRef: 35.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_13:
  label: hue_1m
  standard: 0.0
  leftRef: 10.0
  rightRef: -10.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_14:
  label: hue_6m
  standard: 225.0
  leftRef: 235.0
  rightRef: 215.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
stimulus_15:
  label: hue_2p
  standard: 45.0
  leftRef: 55.0
  rightRef: 35.0
  stairType: simple
  startVal: 3.0
  min_val: 0.2
  max_val: 10.0
  stepType: db
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: 1
  nDown: 1
  startValSd: 10
  pThreshold: 0.63
