monitor:
  name: VIEWPixx_2000A
  size:
  - 1920
  - 1200
  width: 48.4
  distance: 57
depthBits: 8
hue_list: config/colorlist/hue-list-10bit-res0.2-sub-None.npy
patch_nmb: 16
patch_size: 0.75
ref_size: 0.8
field_size:
- 0.4
- 0.4
leftRef.pos:
- -5
- 2.5
rightRef.pos:
- 5
- 2.5
standard.xlim:
- -1.5
- 1.5
standard.ylim:
- 1
- 4
test.xlim:
- -1.5
- 1.5
test.ylim:
- -4
- -1
trial_nmb: 20
trial_dur: 1
