c: 0.12
sscale: 2.6
dlum: 0
noise_condition: L-L
sigma: 2
stimulus_0:
  label: hue_4p
  standard: 135.0
  leftRef: 145.0
  rightRef: 125.0
  stairType: quest
  startVal: 3.0
  min_val: 0.2
  max_val: 10
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 5
  pThreshold: 0.63
stimulus_1:
  label: hue_8m
  standard: 315.0
  leftRef: 325.0
  rightRef: 305.0
  stairType: quest
  startVal: 1.0
  min_val: 0.2
  max_val: 10
  stepType: null
  nReversals: 2
  stepSizes:
  - 2
  - 1
  nUp: null
  nDown: null
  startValSd: 5
  pThreshold: 0.63